version: "3.7"

volumes:
    unit-state:

services:
    composer:
        build: .
        image: liox-shop
        volumes:
            - .:/app
        working_dir: /app
        restart: 'no'
        entrypoint: ["composer"]
        command: ["install", "--no-interaction"]

    web:
        image: liox-shop
        volumes:
            - unit-state:/var/lib/unit/state
            - .:/app
            - .docker/nginx-unit:/docker-entrypoint.d
        working_dir: /app
        restart: unless-stopped
        depends_on:
            - composer
        ports:
            - "8080:8080"

    js-watch:
        image: node:16
        volumes:
            - .:/app
        working_dir: /app
        restart: unless-stopped
        entrypoint: [""]
        command: ["bash", "-c", "npm install && npm run watch"]
