version: "3.7"

volumes:
    unit-state:
    postgres-data:

services:
    web:
        image: ghcr.io/liox-cz/php:8.2
        restart: unless-stopped
        volumes:
            - unit-state:/var/lib/unit/state
            - .:/app
            - .docker/nginx-unit:/docker-entrypoint.d
        depends_on:
            - postgres
        ports:
            - "${LIOX_WEB_PORT:-8080}:8080"
        environment:
            XDEBUG_CONFIG: "${LIOX_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            XDEBUG_MODE: debug
            PHP_IDE_CONFIG: "serverName=liox"

    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: liox
            POSTGRES_PASSWORD: liox
            POSTGRES_DB: liox
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "${LIOX_POSTGRES_PORT:-5432}:5432"

    js-watch:
        image: node:16
        volumes:
            - .:/app
        working_dir: /app
        restart: unless-stopped
        entrypoint: [""]
        command: ["bash", "-c", "npm install && npm run watch"]

    adminer:
        image: adminer:4.8.0
        ports:
            - "${LIOX_ADMINER_PORT:-8000}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        depends_on:
            - postgres
