version: "3.7"

volumes:
    unit-state:

services:
    # Helper service to always have latest composer.lock changes installed
    composer:
        build: .
        image: liox-ai
        volumes:
            - .:/app
        working_dir: /app
        command: "composer install --no-interaction"

    web:
        image: liox-ai
        volumes:
            - unit-state:/var/lib/unit/state
            - .:/app
            - .docker/nginx-unit:/docker-entrypoint.d
        working_dir: /app
        depends_on:
            - composer
            - postgres
        ports:
            - "8080:8080"
