name: Tests

on:
    push:
    pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            coverage: none # default is xdebug
            extensions: mbstring, uuid # needed by phpunit

      -   run: composer install --dev --no-progress
      -   run: npm install
      -   run: npm run dev

      -   run: vendor/bin/phpunit

  phpstan:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v2
            with:
              php-version: 8.2
              coverage: none # default is xdebug
              extensions: mbstring, uuid # needed by phpunit

        -   run: composer install --dev --no-progress

        -   run: composer run-script phpstan
